### ISSUE TITLE
Issue with known hosts

### ISSUE THREAD

**Issue by epinault** [melbahja/goph#10]
I believe this is not completely correct. I have have a host (NAME) I should be saving that first and then the remote IP or both but right now it only save the remote IP.. but the Check for Knownhost seems to use the host rather than IP so I get a mistmatched

 https://github.com/melbahja/goph/blob/f67d58a8a072ab20293fd0813895e7c3130aecf0/hosts.go#L99

Also I was looking at https://www.godoc.org/golang.org/x/crypto/ssh#HostKeyCallback and it seems that It receives the hostname as passed to Dial or NewClientConn

I think the logic should check if host and remote are the same otherwise write the host if not matching

**Comment by epinault** [comment]
Just opened #11 . Feel free to add tests if you d like, Just did via the github interface

**Comment by epinault** [comment]
Looks like you merged #11, any change you can create a release ?

**Comment by melbahja** [comment]
v1.2.0 released :)
Thanks
