### ISSUE TITLE
Need a function that automatically adds host to known_hosts.

### ISSUE THREAD

**Issue by nightan42643** [melbahja/goph#17]
Are you considering adding a function that automatically adds hosts to known_hosts for goph.Config.Callback?

For some controllable internal networks, we basically do not need to consider man-in-the-middle attacks when connecting to the server, and we use other solutions to control user login and record behavior.

**Comment by melbahja** [comment]
You can use `NewUnknown` method.

**Comment by melbahja** [comment]
See: https://github.com/melbahja/goph/blob/master/examples/goph/main.go#L62
And: https://github.com/melbahja/goph/blob/master/examples/goph/main.go#L95
