### ISSUE TITLE
Support two-factor auth with key and password

### ISSUE THREAD

**Issue by qwerty287** [melbahja/goph#36]
Hello!
It seems that goph currently does not support two-factor auth with a key AND a password. See https://security.stackexchange.com/questions/17931/possible-to-use-both-private-key-and-password-authentication-for-ssh-login. Thank you!

**Comment by melbahja** [comment]
You can:

```
       // Start new ssh connection with private key.
	auth, err := goph.Key("/home/mohamed/.ssh/id_rsa", "")
	if err != nil {
		log.Fatal(err)
	}

	pass := goph.Password("Password_HERE")

        // Add password to auth methods.
	auth = append(auth, pass[0])
	
	// Connect
	client, err := goph.New("root", "1.2.3.4", auth)
```

**Comment by Iced-Sun** [comment]
select left(operation.xzqhdm, 12) as xzqhdm, (array_agg([xzqh.mc](http://xzqh.mc/)))[1] as xzqhmc
        , count(distinct [house.id](http://house.id/)) as housenum 
        , count(distinct lock.lockid) filter (where lock.lockid is not null) as locknum
        , count(distinct "user".identifier) filter (where "user".identifier is not null and key.userrole <> '255' and key.keytype in ('0', '2') and key.keystate) as tenantnum
     from "api-ailock-analysis-v1".operation
     join dimension.xzqh
       on operation.xzqhdm = [xzqh.dm](http://xzqh.dm/)
     join "api-ailock-analysis-v1".house
       on [operation.id](http://operation.id/) = house.operation_id 
left join "api-ailock-analysis-v1".lock  
       on [house.id](http://house.id/) = lock.houseid
left join "api-ailock-analysis-v1".key
    using (scope, lockid)
left join "api-ailock-analysis-v1".user "user"
    using (scope, account)
    where length(operation.xzqhdm) >= 12
      and operation.xzqhdm like '330102%'
 group by left(operation.xzqhdm, 12)
