### ISSUE TITLE
Making defaultPath evaluation lazy

### ISSUE THREAD

**Issue by xxzefgh** [melbahja/goph#8]
Would you consider wrapping `defaultPath` in a function? The issue is on Windows environments `HOME` is not set by default. Simple solution would be setting it manually when the program starts:
```go
os.Setenv("HOME", os.Getenv("USERPROFILE"))
```
but it doesn't get recognized by goph since it is evaluated beforehand.

**Comment by xxzefgh** [comment]
I am using this workaround now:
```go
func getConnection(target DeploymentTarget) (*goph.Client, error) {
	callback, err := goph.KnownHosts(os.ExpandEnv("$HOME/.ssh/known_hosts"))
	if err == nil {
		client, err := goph.NewConn(&goph.Config{
			User:     target.Config.User,
			Addr:     target.Config.Address,
			Port:     22,
			Auth:     goph.Password(target.Config.Password),
			Timeout:  goph.DefaultTimeout,
			Callback: callback,
		})

		if err == nil {
			return client, nil
		}
	}

	return nil, err
}

```

**Comment by melbahja** [comment]
hi, thanks for your report.
can you check the pull request fix ?

**Comment by xxzefgh** [comment]
that would probably work but `os/user` prevents cross-compilation, `UserHomeDir` is better option but it's fairly new

**Comment by melbahja** [comment]
Thanks :)

**Comment by xxzefgh** [comment]
@melbahja thank you
